[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000
solc_version = "0.8.20"

[profile.ci]
verbosity = 4

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config